version: '3.8'

services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: verysecurepassword
      MYSQL_DATABASE: test_tremplin
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

  apache:
    image: lavoweb/php-8.3
    ports:
      - "80:80"
    volumes:
       - ./:/var/www        # monte tout le projet sous /var/www
       - ./public:/var/www/html  # mais sert en DocRoot seulement le dossier public/             
    depends_on:
      - db

volumes:
  db_data:
